/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as authValidateCodeRouteImport } from './routes/(auth)/validate-code'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedRefundsRefundIdRouteImport } from './routes/_authenticated/refunds.$refundId'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppNoteNoteIdRouteImport } from './routes/_authenticated/app.note.$noteId'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authValidateCodeRoute = authValidateCodeRouteImport.update({
  id: '/(auth)/validate-code',
  path: '/validate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedRefundsRefundIdRoute =
  AuthenticatedRefundsRefundIdRouteImport.update({
    id: '/refunds/$refundId',
    path: '/refunds/$refundId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNoteNoteIdRoute =
  AuthenticatedAppNoteNoteIdRouteImport.update({
    id: '/note/$noteId',
    path: '/note/$noteId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/validate-code': typeof authValidateCodeRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/$': typeof AdminSplatRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/refunds/$refundId': typeof AuthenticatedRefundsRefundIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/note/$noteId': typeof AuthenticatedAppNoteNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/validate-code': typeof authValidateCodeRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/$': typeof AdminSplatRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/refunds/$refundId': typeof AuthenticatedRefundsRefundIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/note/$noteId': typeof AuthenticatedAppNoteNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/landing': typeof LandingRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/validate-code': typeof authValidateCodeRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/admin/$': typeof AdminSplatRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/refunds/$refundId': typeof AuthenticatedRefundsRefundIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/note/$noteId': typeof AuthenticatedAppNoteNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/validate-code'
    | '/app'
    | '/checkout'
    | '/pricing'
    | '/subscription'
    | '/admin/$'
    | '/app/settings'
    | '/refunds/$refundId'
    | '/app/'
    | '/app/note/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/validate-code'
    | '/checkout'
    | '/pricing'
    | '/subscription'
    | '/admin/$'
    | '/app/settings'
    | '/refunds/$refundId'
    | '/app'
    | '/app/note/$noteId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/landing'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/validate-code'
    | '/_authenticated/app'
    | '/_authenticated/checkout'
    | '/_authenticated/pricing'
    | '/_authenticated/subscription'
    | '/admin/$'
    | '/_authenticated/app/settings'
    | '/_authenticated/refunds/$refundId'
    | '/_authenticated/app/'
    | '/_authenticated/app/note/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LandingRoute: typeof LandingRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authValidateCodeRoute: typeof authValidateCodeRoute
  AdminSplatRoute: typeof AdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/validate-code': {
      id: '/(auth)/validate-code'
      path: '/validate-code'
      fullPath: '/validate-code'
      preLoaderRoute: typeof authValidateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/refunds/$refundId': {
      id: '/_authenticated/refunds/$refundId'
      path: '/refunds/$refundId'
      fullPath: '/refunds/$refundId'
      preLoaderRoute: typeof AuthenticatedRefundsRefundIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/note/$noteId': {
      id: '/_authenticated/app/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/app/note/$noteId'
      preLoaderRoute: typeof AuthenticatedAppNoteNoteIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppNoteNoteIdRoute: typeof AuthenticatedAppNoteNoteIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppNoteNoteIdRoute: AuthenticatedAppNoteNoteIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedRefundsRefundIdRoute: typeof AuthenticatedRefundsRefundIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedRefundsRefundIdRoute: AuthenticatedRefundsRefundIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LandingRoute: LandingRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authValidateCodeRoute: authValidateCodeRoute,
  AdminSplatRoute: AdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
